version: '2.2'
services:
  es-test:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.8.1
    container_name: es-test
    environment:
      - cluster.name=es-test-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
